[project]
name = "Galaxy River Bot"
version = "2.0"
description = "QQ机器人，主要功能是管理群，接入了chatgpt和new bing，加了些娱乐功能"
license = "MIT"
authors = "ASXE"
requires-python = "^3.10"
my_blog_url = "https://asxez.github.io/"
my_box = "2973918177@qq.com"

